# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.convert_text_to_speech_trial_api import ConvertTextToSpeechTrialApi


class TestConvertTextToSpeechTrialApi(unittest.TestCase):
    """ConvertTextToSpeechTrialApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConvertTextToSpeechTrialApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_convert_text_to_speech_trial(self) -> None:
        """Test case for cancel_convert_text_to_speech_trial

        CancelConvertTextToSpeechTrial
        """
        pass

    def test_get_convert_text_to_speech_trial(self) -> None:
        """Test case for get_convert_text_to_speech_trial

        GetConvertTextToSpeechTrial
        """
        pass

    def test_post_convert_text_to_speech_trial(self) -> None:
        """Test case for post_convert_text_to_speech_trial

        PostConvertTextToSpeechTrial
        """
        pass


if __name__ == '__main__':
    unittest.main()
