# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.upscale_image_api import UpscaleImageApi


class TestUpscaleImageApi(unittest.TestCase):
    """UpscaleImageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UpscaleImageApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_upscale_image(self) -> None:
        """Test case for cancel_upscale_image

        CancelUpscaleImage
        """
        pass

    def test_get_upscale_image(self) -> None:
        """Test case for get_upscale_image

        GetUpscaleImage
        """
        pass

    def test_post_upscale_image(self) -> None:
        """Test case for post_upscale_image

        PostUpscaleImage
        """
        pass


if __name__ == '__main__':
    unittest.main()
