# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.deskew_image_api import DeskewImageApi


class TestDeskewImageApi(unittest.TestCase):
    """DeskewImageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeskewImageApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_deskew_image(self) -> None:
        """Test case for cancel_deskew_image

        CancelDeskewImage
        """
        pass

    def test_get_deskew_image(self) -> None:
        """Test case for get_deskew_image

        GetDeskewImage
        """
        pass

    def test_post_deskew_image(self) -> None:
        """Test case for post_deskew_image

        PostDeskewImage
        """
        pass


if __name__ == '__main__':
    unittest.main()
