# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.detect_regions_api import DetectRegionsApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestDetectRegionsApi(unittest.TestCase):
    """DetectRegionsApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.detect_regions_api.DetectRegionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_detect_regions(self):
        """Test case for cancel_detect_regions

        CancelDetectRegions  # noqa: E501
        """
        pass

    def test_get_detect_regions(self):
        """Test case for get_detect_regions

        GetDetectRegions  # noqa: E501
        """
        pass

    def test_post_detect_regions(self):
        """Test case for post_detect_regions

        PostDetectRegions  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
