# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.text_to_speech_api import TextToSpeechApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestTextToSpeechApi(unittest.TestCase):
    """TextToSpeechApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.text_to_speech_api.TextToSpeechApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_text_to_speech_result(self):
        """Test case for get_text_to_speech_result

        GetTextToSpeechResult  # noqa: E501
        """
        pass

    def test_get_text_to_speech_result_file(self):
        """Test case for get_text_to_speech_result_file

        GetTextToSpeechResultFile  # noqa: E501
        """
        pass

    def test_post_text_to_speech(self):
        """Test case for post_text_to_speech

        PostTextToSpeech  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
