# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.recognize_pdf_api import RecognizePdfApi


class TestRecognizePdfApi(unittest.TestCase):
    """RecognizePdfApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecognizePdfApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_recognize_pdf(self) -> None:
        """Test case for cancel_recognize_pdf

        CancelRecognizePdf
        """
        pass

    def test_get_recognize_pdf(self) -> None:
        """Test case for get_recognize_pdf

        GetRecognizePdf
        """
        pass

    def test_post_recognize_pdf(self) -> None:
        """Test case for post_recognize_pdf

        PostRecognizePdf
        """
        pass


if __name__ == '__main__':
    unittest.main()
