# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.dewarp_image_api import DewarpImageApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestDewarpImageApi(unittest.TestCase):
    """DewarpImageApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.dewarp_image_api.DewarpImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_dewarp_image(self):
        """Test case for cancel_dewarp_image

        CancelDewarpImage  # noqa: E501
        """
        pass

    def test_get_dewarp_image(self):
        """Test case for get_dewarp_image

        GetDewarpImage  # noqa: E501
        """
        pass

    def test_post_dewarp_image(self):
        """Test case for post_dewarp_image

        PostDewarpImage  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
