# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.upscale_image_api import UpscaleImageApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestUpscaleImageApi(unittest.TestCase):
    """UpscaleImageApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.upscale_image_api.UpscaleImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_upscale_image(self):
        """Test case for cancel_upscale_image

        CancelUpscaleImage  # noqa: E501
        """
        pass

    def test_get_upscale_image(self):
        """Test case for get_upscale_image

        GetUpscaleImage  # noqa: E501
        """
        pass

    def test_post_upscale_image(self):
        """Test case for post_upscale_image

        PostUpscaleImage  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
