# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.binarize_image_api import BinarizeImageApi


class TestBinarizeImageApi(unittest.TestCase):
    """BinarizeImageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = BinarizeImageApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_binarize_image(self) -> None:
        """Test case for cancel_binarize_image

        CancelBinarizeImage
        """
        pass

    def test_get_binarize_image(self) -> None:
        """Test case for get_binarize_image

        GetBinarizeImage
        """
        pass

    def test_post_binarize_image(self) -> None:
        """Test case for post_binarize_image

        PostBinarizeImage
        """
        pass


if __name__ == '__main__':
    unittest.main()
