# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.detect_regions_api import DetectRegionsApi


class TestDetectRegionsApi(unittest.TestCase):
    """DetectRegionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DetectRegionsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_detect_regions(self) -> None:
        """Test case for cancel_detect_regions

        CancelDetectRegions
        """
        pass

    def test_get_detect_regions(self) -> None:
        """Test case for get_detect_regions

        GetDetectRegions
        """
        pass

    def test_post_detect_regions(self) -> None:
        """Test case for post_detect_regions

        PostDetectRegions
        """
        pass


if __name__ == '__main__':
    unittest.main()
