# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.recognize_table_api import RecognizeTableApi


class TestRecognizeTableApi(unittest.TestCase):
    """RecognizeTableApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecognizeTableApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_recognize_table(self) -> None:
        """Test case for cancel_recognize_table

        CancelRecognizeTable
        """
        pass

    def test_get_recognize_table(self) -> None:
        """Test case for get_recognize_table

        GetRecognizeTable
        """
        pass

    def test_post_recognize_table(self) -> None:
        """Test case for post_recognize_table

        PostRecognizeTable
        """
        pass


if __name__ == '__main__':
    unittest.main()
