# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.convert_text_to_speech_api import ConvertTextToSpeechApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestConvertTextToSpeechApi(unittest.TestCase):
    """ConvertTextToSpeechApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.convert_text_to_speech_api.ConvertTextToSpeechApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_convert_text_to_speech(self):
        """Test case for cancel_convert_text_to_speech

        CancelConvertTextToSpeech  # noqa: E501
        """
        pass

    def test_get_convert_text_to_speech(self):
        """Test case for get_convert_text_to_speech

        GetConvertTextToSpeech  # noqa: E501
        """
        pass

    def test_post_convert_text_to_speech(self):
        """Test case for post_convert_text_to_speech

        PostConvertTextToSpeech  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
