# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.identify_font_api import IdentifyFontApi


class TestIdentifyFontApi(unittest.TestCase):
    """IdentifyFontApi unit test stubs"""

    def setUp(self) -> None:
        self.api = IdentifyFontApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_identify_font(self) -> None:
        """Test case for cancel_identify_font

        CancelIdentifyFont
        """
        pass

    def test_get_identify_font(self) -> None:
        """Test case for get_identify_font

        GetIdentifyFont
        """
        pass

    def test_post_identify_font(self) -> None:
        """Test case for post_identify_font

        PostIdentifyFont
        """
        pass


if __name__ == '__main__':
    unittest.main()
