# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.recognize_label_api import RecognizeLabelApi


class TestRecognizeLabelApi(unittest.TestCase):
    """RecognizeLabelApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecognizeLabelApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_recognize_label(self) -> None:
        """Test case for cancel_recognize_label

        CancelRecognizeLabel
        """
        pass

    def test_get_recognize_label(self) -> None:
        """Test case for get_recognize_label

        GetRecognizeLabel
        """
        pass

    def test_post_recognize_label(self) -> None:
        """Test case for post_recognize_label

        PostRecognizeLabel
        """
        pass


if __name__ == '__main__':
    unittest.main()
