# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.dj_vu2_pdf_api import DjVu2PDFApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestDjVu2PDFApi(unittest.TestCase):
    """DjVu2PDFApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.dj_vu2_pdf_api.DjVu2PDFApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_dj_vu2_pdf(self):
        """Test case for cancel_dj_vu2_pdf

        CancelDjVu2PDF  # noqa: E501
        """
        pass

    def test_get_dj_vu2_pdf(self):
        """Test case for get_dj_vu2_pdf

        GetDjVu2PDF  # noqa: E501
        """
        pass

    def test_post_dj_vu2_pdf(self):
        """Test case for post_dj_vu2_pdf

        PostDjVu2PDF  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
