# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.image_processing_api import ImageProcessingApi


class TestImageProcessingApi(unittest.TestCase):
    """ImageProcessingApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ImageProcessingApi()

    def tearDown(self) -> None:
        pass

    def test_get_result_file(self) -> None:
        """Test case for get_result_file

        GetResultFile
        """
        pass

    def test_get_result_task(self) -> None:
        """Test case for get_result_task

        GetResultTask
        """
        pass

    def test_post_binarization_file(self) -> None:
        """Test case for post_binarization_file

        PostBinarizationFile
        """
        pass

    def test_post_dewarping_file(self) -> None:
        """Test case for post_dewarping_file

        PostDewarpingFile
        """
        pass

    def test_post_skew_correction_file(self) -> None:
        """Test case for post_skew_correction_file

        PostSkewCorrectionFile
        """
        pass

    def test_post_upsampling_file(self) -> None:
        """Test case for post_upsampling_file

        PostUpsamplingImageFile
        """
        pass


if __name__ == '__main__':
    unittest.main()
