# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.convert_text_to_speech_api import ConvertTextToSpeechApi


class TestConvertTextToSpeechApi(unittest.TestCase):
    """ConvertTextToSpeechApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ConvertTextToSpeechApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_convert_text_to_speech(self) -> None:
        """Test case for cancel_convert_text_to_speech

        CancelConvertTextToSpeech
        """
        pass

    def test_get_convert_text_to_speech(self) -> None:
        """Test case for get_convert_text_to_speech

        GetConvertTextToSpeech
        """
        pass

    def test_post_convert_text_to_speech(self) -> None:
        """Test case for post_convert_text_to_speech

        PostConvertTextToSpeech
        """
        pass


if __name__ == '__main__':
    unittest.main()
