# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.utilities_api import UtilitiesApi


class TestUtilitiesApi(unittest.TestCase):
    """UtilitiesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = UtilitiesApi()

    def tearDown(self) -> None:
        pass

    def test_get_task_status(self) -> None:
        """Test case for get_task_status

        GetTaskStatus
        """
        pass


if __name__ == '__main__':
    unittest.main()
