# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.dewarp_image_api import DewarpImageApi


class TestDewarpImageApi(unittest.TestCase):
    """DewarpImageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DewarpImageApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_dewarp_image(self) -> None:
        """Test case for cancel_dewarp_image

        CancelDewarpImage
        """
        pass

    def test_get_dewarp_image(self) -> None:
        """Test case for get_dewarp_image

        GetDewarpImage
        """
        pass

    def test_post_dewarp_image(self) -> None:
        """Test case for post_dewarp_image

        PostDewarpImage
        """
        pass


if __name__ == '__main__':
    unittest.main()
