# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.text_to_speech_api import TextToSpeechApi


class TestTextToSpeechApi(unittest.TestCase):
    """TextToSpeechApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TextToSpeechApi()

    def tearDown(self) -> None:
        pass

    def test_get_text_to_speech_result(self) -> None:
        """Test case for get_text_to_speech_result

        GetTextToSpeechResult
        """
        pass

    def test_get_text_to_speech_result_file(self) -> None:
        """Test case for get_text_to_speech_result_file

        GetTextToSpeechResultFile
        """
        pass

    def test_post_text_to_speech(self) -> None:
        """Test case for post_text_to_speech

        PostTextToSpeech
        """
        pass


if __name__ == '__main__':
    unittest.main()
