# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.deskew_image_api import DeskewImageApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestDeskewImageApi(unittest.TestCase):
    """DeskewImageApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.deskew_image_api.DeskewImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_deskew_image(self):
        """Test case for cancel_deskew_image

        CancelDeskewImage  # noqa: E501
        """
        pass

    def test_get_deskew_image(self):
        """Test case for get_deskew_image

        GetDeskewImage  # noqa: E501
        """
        pass

    def test_post_deskew_image(self):
        """Test case for post_deskew_image

        PostDeskewImage  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
