# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.recognize_image_api import RecognizeImageApi


class TestRecognizeImageApi(unittest.TestCase):
    """RecognizeImageApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RecognizeImageApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_recognize_image(self) -> None:
        """Test case for cancel_recognize_image

        CancelRecognizeImage
        """
        pass

    def test_get_recognize_image(self) -> None:
        """Test case for get_recognize_image

        GetRecognizeImage
        """
        pass

    def test_post_recognize_image(self) -> None:
        """Test case for post_recognize_image

        PostRecognizeImage
        """
        pass


if __name__ == '__main__':
    unittest.main()
