# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from aspose_ocr_cloud.api.dj_vu2_pdf_api import DjVu2PDFApi


class TestDjVu2PDFApi(unittest.TestCase):
    """DjVu2PDFApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DjVu2PDFApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_dj_vu2_pdf(self) -> None:
        """Test case for cancel_dj_vu2_pdf

        CancelDjVu2PDF
        """
        pass

    def test_get_dj_vu2_pdf(self) -> None:
        """Test case for get_dj_vu2_pdf

        GetDjVu2PDF
        """
        pass

    def test_post_dj_vu2_pdf(self) -> None:
        """Test case for post_dj_vu2_pdf

        PostDjVu2PDF
        """
        pass


if __name__ == '__main__':
    unittest.main()
