# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.recognize_table_api import RecognizeTableApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestRecognizeTableApi(unittest.TestCase):
    """RecognizeTableApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.recognize_table_api.RecognizeTableApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_recognize_table(self):
        """Test case for cancel_recognize_table

        CancelRecognizeTable  # noqa: E501
        """
        pass

    def test_get_recognize_table(self):
        """Test case for get_recognize_table

        GetRecognizeTable  # noqa: E501
        """
        pass

    def test_post_recognize_table(self):
        """Test case for post_recognize_table

        PostRecognizeTable  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
