# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.identify_font_api import IdentifyFontApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestIdentifyFontApi(unittest.TestCase):
    """IdentifyFontApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.identify_font_api.IdentifyFontApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_identify_font(self):
        """Test case for cancel_identify_font

        CancelIdentifyFont  # noqa: E501
        """
        pass

    def test_get_identify_font(self):
        """Test case for get_identify_font

        GetIdentifyFont  # noqa: E501
        """
        pass

    def test_post_identify_font(self):
        """Test case for post_identify_font

        PostIdentifyFont  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
