# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import absolute_import

import unittest

import aspose_ocr_cloud
from aspose_ocr_cloud.api.binarize_image_api import BinarizeImageApi  # noqa: E501
from aspose_ocr_cloud.rest import ApiException


class TestBinarizeImageApi(unittest.TestCase):
    """BinarizeImageApi unit test stubs"""

    def setUp(self):
        self.api = aspose_ocr_cloud.api.binarize_image_api.BinarizeImageApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cancel_binarize_image(self):
        """Test case for cancel_binarize_image

        CancelBinarizeImage  # noqa: E501
        """
        pass

    def test_get_binarize_image(self):
        """Test case for get_binarize_image

        GetBinarizeImage  # noqa: E501
        """
        pass

    def test_post_binarize_image(self):
        """Test case for post_binarize_image

        PostBinarizeImage  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
