# flake8: noqa

# import apis into api package
from aspose_ocr_cloud.api.binarize_image_api import BinarizeImageApi
from aspose_ocr_cloud.api.convert_text_to_speech_api import ConvertTextToSpeechApi
from aspose_ocr_cloud.api.convert_text_to_speech_trial_api import ConvertTextToSpeechTrialApi
from aspose_ocr_cloud.api.deskew_image_api import DeskewImageApi
from aspose_ocr_cloud.api.detect_regions_api import DetectRegionsApi
from aspose_ocr_cloud.api.dewarp_image_api import DewarpImageApi
from aspose_ocr_cloud.api.dj_vu2_pdf_api import DjVu2PDFApi
from aspose_ocr_cloud.api.identify_font_api import IdentifyFontApi
from aspose_ocr_cloud.api.image_processing_api import ImageProcessingApi
from aspose_ocr_cloud.api.recognize_and_parse_invoice_api import RecognizeAndParseInvoiceApi
from aspose_ocr_cloud.api.recognize_image_api import RecognizeImageApi
from aspose_ocr_cloud.api.recognize_image_trial_api import RecognizeImageTrialApi
from aspose_ocr_cloud.api.recognize_label_api import RecognizeLabelApi
from aspose_ocr_cloud.api.recognize_pdf_api import RecognizePdfApi
from aspose_ocr_cloud.api.recognize_receipt_api import RecognizeReceiptApi
from aspose_ocr_cloud.api.recognize_regions_api import RecognizeRegionsApi
from aspose_ocr_cloud.api.recognize_table_api import RecognizeTableApi
from aspose_ocr_cloud.api.text_to_speech_api import TextToSpeechApi
from aspose_ocr_cloud.api.upscale_image_api import UpscaleImageApi
from aspose_ocr_cloud.api.utilities_api import UtilitiesApi

