# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from aspose_ocr_cloud.paths.v5_0_ocr_convert_text_to_speech_trial.delete import CancelConvertTextToSpeechTrial
from aspose_ocr_cloud.paths.v5_0_ocr_convert_text_to_speech_trial.get import GetConvertTextToSpeechTrial
from aspose_ocr_cloud.paths.v5_0_ocr_convert_text_to_speech_trial.post import PostConvertTextToSpeechTrial


class ConvertTextToSpeechTrialApi(
    CancelConvertTextToSpeechTrial,
    GetConvertTextToSpeechTrial,
    PostConvertTextToSpeechTrial,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
