# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from aspose_ocr_cloud.paths.v5_0_ocr_detect_regions.delete import CancelDetectRegions
from aspose_ocr_cloud.paths.v5_0_ocr_detect_regions.get import GetDetectRegions
from aspose_ocr_cloud.paths.v5_0_ocr_detect_regions.post import PostDetectRegions


class DetectRegionsApi(
    CancelDetectRegions,
    GetDetectRegions,
    PostDetectRegions,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
