# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from aspose_ocr_cloud.paths.v5_0_ocr_dewarp_image.delete import CancelDewarpImage
from aspose_ocr_cloud.paths.v5_0_ocr_dewarp_image.get import GetDewarpImage
from aspose_ocr_cloud.paths.v5_0_ocr_dewarp_image.post import PostDewarpImage


class DewarpImageApi(
    CancelDewarpImage,
    GetDewarpImage,
    PostDewarpImage,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
