# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from aspose_ocr_cloud.paths.v5_0_ocr_dj_vu2_pdf.delete import CancelDjVu2Pdf
from aspose_ocr_cloud.paths.v5_0_ocr_dj_vu2_pdf.get import GetDjVu2Pdf
from aspose_ocr_cloud.paths.v5_0_ocr_dj_vu2_pdf.post import PostDjVu2Pdf


class DjVu2PDFApi(
    CancelDjVu2Pdf,
    GetDjVu2Pdf,
    PostDjVu2Pdf,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
