# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from aspose_ocr_cloud.paths.v5_0_ocr_image_processing_get_result_file.get import GetResultFile
from aspose_ocr_cloud.paths.v5_0_ocr_image_processing_get_result_task.get import GetResultTask
from aspose_ocr_cloud.paths.v5_0_ocr_image_processing_post_binarization_file.post import PostBinarizationFile
from aspose_ocr_cloud.paths.v5_0_ocr_image_processing_post_dewarping_file.post import PostDewarpingFile
from aspose_ocr_cloud.paths.v5_0_ocr_image_processing_post_skew_correction_file.post import PostSkewCorrectionFile
from aspose_ocr_cloud.paths.v5_0_ocr_image_processing_post_upsampling_image_file.post import PostUpsamplingFile


class ImageProcessingApi(
    GetResultFile,
    GetResultTask,
    PostBinarizationFile,
    PostDewarpingFile,
    PostSkewCorrectionFile,
    PostUpsamplingFile,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
