# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from aspose_ocr_cloud.paths.v5_0_ocr_recognize_pdf.delete import CancelRecognizePdf
from aspose_ocr_cloud.paths.v5_0_ocr_recognize_pdf.get import GetRecognizePdf
from aspose_ocr_cloud.paths.v5_0_ocr_recognize_pdf.post import PostRecognizePdf


class RecognizePdfApi(
    CancelRecognizePdf,
    GetRecognizePdf,
    PostRecognizePdf,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
