# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from aspose_ocr_cloud.paths.v5_0_ocr_text_to_speech_get_text_to_speech_result.get import GetTextToSpeechResult
from aspose_ocr_cloud.paths.v5_0_ocr_text_to_speech_get_text_to_speech_result_file.get import GetTextToSpeechResultFile
from aspose_ocr_cloud.paths.v5_0_ocr_text_to_speech_post_text_to_speech.post import PostTextToSpeech


class TextToSpeechApi(
    GetTextToSpeechResult,
    GetTextToSpeechResultFile,
    PostTextToSpeech,
):
    """NOTE: This class is auto generated by OpenAPI Generator
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """
    pass
