# coding: utf-8

# flake8: noqa

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

__version__ = "23.11.0"

# import ApiClient
from aspose_ocr_cloud.api_client import ApiClient

# import Configuration
from aspose_ocr_cloud.configuration import Configuration

# import exceptions
from aspose_ocr_cloud.exceptions import OpenApiException
from aspose_ocr_cloud.exceptions import ApiAttributeError
from aspose_ocr_cloud.exceptions import ApiTypeError
from aspose_ocr_cloud.exceptions import ApiValueError
from aspose_ocr_cloud.exceptions import ApiKeyError
from aspose_ocr_cloud.exceptions import ApiException
