# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API

    The version of the OpenAPI document: 5.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OCRTaskStatus(str, Enum):
    """
    Task status
    """

    """
    allowed enum values
    """
    PENDING = 'Pending'
    PROCESSING = 'Processing'
    COMPLETED = 'Completed'
    ERROR = 'Error'
    NOTEXIST = 'NotExist'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OCRTaskStatus from a JSON string"""
        return cls(json.loads(json_str))


