# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aspose_ocr_cloud import schemas  # noqa: F401


class DsrMode(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Option that sets the recognition result type or combination of some types: Text, Searchable PDF, HOCR
    """


    class MetaOapg:
        enum_value_to_name = {
            "Regions": "REGIONS",
            "DsrNoFilter": "DSR_NO_FILTER",
            "DsrAndFilter": "DSR_AND_FILTER",
            "NoDsrNoFilter": "NO_DSR_NO_FILTER",
            "TextDetector": "TEXT_DETECTOR",
            "DsrPlusDetector": "DSR_PLUS_DETECTOR",
            "PolygonalTextDetector": "POLYGONAL_TEXT_DETECTOR",
        }
    
    @schemas.classproperty
    def REGIONS(cls):
        return cls("Regions")
    
    @schemas.classproperty
    def DSR_NO_FILTER(cls):
        return cls("DsrNoFilter")
    
    @schemas.classproperty
    def DSR_AND_FILTER(cls):
        return cls("DsrAndFilter")
    
    @schemas.classproperty
    def NO_DSR_NO_FILTER(cls):
        return cls("NoDsrNoFilter")
    
    @schemas.classproperty
    def TEXT_DETECTOR(cls):
        return cls("TextDetector")
    
    @schemas.classproperty
    def DSR_PLUS_DETECTOR(cls):
        return cls("DsrPlusDetector")
    
    @schemas.classproperty
    def POLYGONAL_TEXT_DETECTOR(cls):
        return cls("PolygonalTextDetector")
