# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aspose_ocr_cloud import schemas  # noqa: F401


class Language(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Recognition Language
    """


    class MetaOapg:
        enum_value_to_name = {
            "English": "ENGLISH",
            "German": "GERMAN",
            "French": "FRENCH",
            "Italian": "ITALIAN",
            "Spanish": "SPANISH",
            "Portuguese": "PORTUGUESE",
            "Polish": "POLISH",
            "Slovene": "SLOVENE",
            "Slovak": "SLOVAK",
            "Netherlands": "NETHERLANDS",
            "Lithuanian": "LITHUANIAN",
            "Latvian": "LATVIAN",
            "Danish": "DANISH",
            "Norwegian": "NORWEGIAN",
            "Finnish": "FINNISH",
            "Serbian": "SERBIAN",
            "Croatian": "CROATIAN",
            "Czech": "CZECH",
            "Swedish": "SWEDISH",
            "Estonian": "ESTONIAN",
            "Romanian": "ROMANIAN",
            "Chinese": "CHINESE",
            "Russian": "RUSSIAN",
            "Arabic": "ARABIC",
            "Hindi": "HINDI",
            "Ukrainan": "UKRAINAN",
            "Bengali": "BENGALI",
            "Tibetan": "TIBETAN",
            "Thai": "THAI",
            "Urdu": "URDU",
            "Turkish": "TURKISH",
            "Korean": "KOREAN",
            "Indonesian": "INDONESIAN",
            "Hebrew": "HEBREW",
            "Javanese": "JAVANESE",
            "Greek": "GREEK",
            "Japanese": "JAPANESE",
            "Persian": "PERSIAN",
            "Albanian": "ALBANIAN",
            "Latin": "LATIN",
            "Vietnamese": "VIETNAMESE",
            "Uzbek": "UZBEK",
            "Georgian": "GEORGIAN",
            "Bulgarian": "BULGARIAN",
            "Azerbaijani": "AZERBAIJANI",
            "Kazah": "KAZAH",
            "Macedonian": "MACEDONIAN",
            "Belorussian": "BELORUSSIAN",
            "HWT_eng": "HWT_ENG",
        }
    
    @schemas.classproperty
    def ENGLISH(cls):
        return cls("English")
    
    @schemas.classproperty
    def GERMAN(cls):
        return cls("German")
    
    @schemas.classproperty
    def FRENCH(cls):
        return cls("French")
    
    @schemas.classproperty
    def ITALIAN(cls):
        return cls("Italian")
    
    @schemas.classproperty
    def SPANISH(cls):
        return cls("Spanish")
    
    @schemas.classproperty
    def PORTUGUESE(cls):
        return cls("Portuguese")
    
    @schemas.classproperty
    def POLISH(cls):
        return cls("Polish")
    
    @schemas.classproperty
    def SLOVENE(cls):
        return cls("Slovene")
    
    @schemas.classproperty
    def SLOVAK(cls):
        return cls("Slovak")
    
    @schemas.classproperty
    def NETHERLANDS(cls):
        return cls("Netherlands")
    
    @schemas.classproperty
    def LITHUANIAN(cls):
        return cls("Lithuanian")
    
    @schemas.classproperty
    def LATVIAN(cls):
        return cls("Latvian")
    
    @schemas.classproperty
    def DANISH(cls):
        return cls("Danish")
    
    @schemas.classproperty
    def NORWEGIAN(cls):
        return cls("Norwegian")
    
    @schemas.classproperty
    def FINNISH(cls):
        return cls("Finnish")
    
    @schemas.classproperty
    def SERBIAN(cls):
        return cls("Serbian")
    
    @schemas.classproperty
    def CROATIAN(cls):
        return cls("Croatian")
    
    @schemas.classproperty
    def CZECH(cls):
        return cls("Czech")
    
    @schemas.classproperty
    def SWEDISH(cls):
        return cls("Swedish")
    
    @schemas.classproperty
    def ESTONIAN(cls):
        return cls("Estonian")
    
    @schemas.classproperty
    def ROMANIAN(cls):
        return cls("Romanian")
    
    @schemas.classproperty
    def CHINESE(cls):
        return cls("Chinese")
    
    @schemas.classproperty
    def RUSSIAN(cls):
        return cls("Russian")
    
    @schemas.classproperty
    def ARABIC(cls):
        return cls("Arabic")
    
    @schemas.classproperty
    def HINDI(cls):
        return cls("Hindi")
    
    @schemas.classproperty
    def UKRAINAN(cls):
        return cls("Ukrainan")
    
    @schemas.classproperty
    def BENGALI(cls):
        return cls("Bengali")
    
    @schemas.classproperty
    def TIBETAN(cls):
        return cls("Tibetan")
    
    @schemas.classproperty
    def THAI(cls):
        return cls("Thai")
    
    @schemas.classproperty
    def URDU(cls):
        return cls("Urdu")
    
    @schemas.classproperty
    def TURKISH(cls):
        return cls("Turkish")
    
    @schemas.classproperty
    def KOREAN(cls):
        return cls("Korean")
    
    @schemas.classproperty
    def INDONESIAN(cls):
        return cls("Indonesian")
    
    @schemas.classproperty
    def HEBREW(cls):
        return cls("Hebrew")
    
    @schemas.classproperty
    def JAVANESE(cls):
        return cls("Javanese")
    
    @schemas.classproperty
    def GREEK(cls):
        return cls("Greek")
    
    @schemas.classproperty
    def JAPANESE(cls):
        return cls("Japanese")
    
    @schemas.classproperty
    def PERSIAN(cls):
        return cls("Persian")
    
    @schemas.classproperty
    def ALBANIAN(cls):
        return cls("Albanian")
    
    @schemas.classproperty
    def LATIN(cls):
        return cls("Latin")
    
    @schemas.classproperty
    def VIETNAMESE(cls):
        return cls("Vietnamese")
    
    @schemas.classproperty
    def UZBEK(cls):
        return cls("Uzbek")
    
    @schemas.classproperty
    def GEORGIAN(cls):
        return cls("Georgian")
    
    @schemas.classproperty
    def BULGARIAN(cls):
        return cls("Bulgarian")
    
    @schemas.classproperty
    def AZERBAIJANI(cls):
        return cls("Azerbaijani")
    
    @schemas.classproperty
    def KAZAH(cls):
        return cls("Kazah")
    
    @schemas.classproperty
    def MACEDONIAN(cls):
        return cls("Macedonian")
    
    @schemas.classproperty
    def BELORUSSIAN(cls):
        return cls("Belorussian")
    
    @schemas.classproperty
    def HWT_ENG(cls):
        return cls("HWT_eng")
