# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aspose_ocr_cloud import schemas  # noqa: F401


class ResponseStatusCode(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Status code showing the status of the request, operation, and result processing.
    """


    class MetaOapg:
        enum_value_to_name = {
            "Ok": "OK",
            "PartiallyNotFound": "PARTIALLY_NOT_FOUND",
            "NoAnyResultData": "NO_ANY_RESULT_DATA",
            "ResultDataLost": "RESULT_DATA_LOST",
            "TaskNotFound": "TASK_NOT_FOUND",
            "NotReady": "NOT_READY",
            "Error": "ERROR",
        }
    
    @schemas.classproperty
    def OK(cls):
        return cls("Ok")
    
    @schemas.classproperty
    def PARTIALLY_NOT_FOUND(cls):
        return cls("PartiallyNotFound")
    
    @schemas.classproperty
    def NO_ANY_RESULT_DATA(cls):
        return cls("NoAnyResultData")
    
    @schemas.classproperty
    def RESULT_DATA_LOST(cls):
        return cls("ResultDataLost")
    
    @schemas.classproperty
    def TASK_NOT_FOUND(cls):
        return cls("TaskNotFound")
    
    @schemas.classproperty
    def NOT_READY(cls):
        return cls("NotReady")
    
    @schemas.classproperty
    def ERROR(cls):
        return cls("Error")
