# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aspose_ocr_cloud import schemas  # noqa: F401


class TTSBodyDeprecated(
    schemas.DictSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    Represents input text data with settings
    """


    class MetaOapg:
        required = {
            "language",
            "text",
            "resultType",
        }
        
        class properties:
            
            
            class text(
                schemas.StrSchema
            ):
            
            
                class MetaOapg:
                    min_length = 1
        
            @staticmethod
            def language() -> typing.Type['LanguageTTS']:
                return LanguageTTS
        
            @staticmethod
            def resultType() -> typing.Type['ResultTypeTTS']:
                return ResultTypeTTS
            __annotations__ = {
                "text": text,
                "language": language,
                "resultType": resultType,
            }
        additional_properties = schemas.NotAnyTypeSchema
    
    language: 'LanguageTTS'
    text: MetaOapg.properties.text
    resultType: 'ResultTypeTTS'
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["language"]) -> 'LanguageTTS': ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["text"]) -> MetaOapg.properties.text: ...
    
    @typing.overload
    def __getitem__(self, name: typing_extensions.Literal["resultType"]) -> 'ResultTypeTTS': ...
    
    def __getitem__(self, name: typing.Union[typing_extensions.Literal["language"], typing_extensions.Literal["text"], typing_extensions.Literal["resultType"], ]):
        # dict_instance[name] accessor
        return super().__getitem__(name)
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["language"]) -> 'LanguageTTS': ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["text"]) -> MetaOapg.properties.text: ...
    
    @typing.overload
    def get_item_oapg(self, name: typing_extensions.Literal["resultType"]) -> 'ResultTypeTTS': ...
    
    def get_item_oapg(self, name: typing.Union[typing_extensions.Literal["language"], typing_extensions.Literal["text"], typing_extensions.Literal["resultType"], ]):
        return super().get_item_oapg(name)

    def __new__(
        cls,
        *_args: typing.Union[dict, frozendict.frozendict, ],
        language: 'LanguageTTS',
        text: typing.Union[MetaOapg.properties.text, str, ],
        resultType: 'ResultTypeTTS',
        _configuration: typing.Optional[schemas.Configuration] = None,
    ) -> 'TTSBodyDeprecated':
        return super().__new__(
            cls,
            *_args,
            language=language,
            text=text,
            resultType=resultType,
            _configuration=_configuration,
        )

from aspose_ocr_cloud.model.language_tts import LanguageTTS
from aspose_ocr_cloud.model.result_type_tts import ResultTypeTTS
