# coding: utf-8

"""
    Aspose OCR Cloud 5.0 API

    Aspose OCR Cloud 5.0 API  # noqa: E501

    The version of the OpenAPI document: 5.0
    Generated by: https://openapi-generator.tech
"""

from datetime import date, datetime  # noqa: F401
import decimal  # noqa: F401
import functools  # noqa: F401
import io  # noqa: F401
import re  # noqa: F401
import typing  # noqa: F401
import typing_extensions  # noqa: F401
import uuid  # noqa: F401

import frozendict  # noqa: F401

from aspose_ocr_cloud import schemas  # noqa: F401


class TTSTaskStatus(
    schemas.EnumBase,
    schemas.StrSchema
):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.

    TTS Task status
    """


    class MetaOapg:
        enum_value_to_name = {
            "Pending": "PENDING",
            "Processing": "PROCESSING",
            "Completed": "COMPLETED",
            "Error": "ERROR",
            "NotExist": "NOT_EXIST",
        }
    
    @schemas.classproperty
    def PENDING(cls):
        return cls("Pending")
    
    @schemas.classproperty
    def PROCESSING(cls):
        return cls("Processing")
    
    @schemas.classproperty
    def COMPLETED(cls):
        return cls("Completed")
    
    @schemas.classproperty
    def ERROR(cls):
        return cls("Error")
    
    @schemas.classproperty
    def NOT_EXIST(cls):
        return cls("NotExist")
